### PR TITLE
FFWEB-904- FF\Communication block disables FPC cache for a whole site #36

### PR DESCRIPTION
**Pull request by a-laurowski**
Add ff-comunication as new customer section and reload it at each visit making it no-cacheable content

- Solves issue: #36

### CODE REVIEW

**Comment by fritzmg** [comment]
Perfect 👍

**Comment by fritzmg** [comment]
Have these changes been tested? They do not work in our Magento installation:

fferror

**Comment by a-laurowski** [comment]
Hi @fritzmg  
This change has been tested with all Magento 2.2.2+  versions.
Could You tell me how to reproduce this situation?

Also, can I ask You for answering few questions. They could be  helpful with solving that issue:
- What Magneto2 version do You use?
- Does the ff-communication component is present in DOM at the moment these errors occurs?
- What file and line this "TypeError: e.url is undefined" is point to?
- Are these errors present in all web browsers?

**Comment by a-laurowski** [comment]
Hi @fritzmg 
Can You clear Your web browser cache and check again?
I was able to reproduce error You mentioned but only when I've passed older version of
Omikron/Factfinder/view/frontend/web/js/view/ffcommunication.js
or if file was removed totally
err
but restoring file or reverting to current version make this error disappear and communication works correctly
przechwytywanie2

**Comment by fritzmg** [comment]
I see :). I'll test.

**Comment by fritzmg** [comment]
> What Magneto2 version do You use?

2.2.6

> Does the ff-communication component is present in DOM at the moment these errors occurs?

The `<ff-communication>` component is present in the DOM. I can't tell if it's already present in the DOM when these errors occur.

> What file and line this "TypeError: e.url is undefined" is point to?

All in `Omikron_Factfinder/ff-web-components/dist/elements.build.js`.

> Are these errors presents in all web browsers?

More or less. Different browsers complain about different things not being present. While it is `e.url` in Firefox, Chrome shows
```
elements.build.js:8 Uncaught TypeError: Cannot read property 'length' of undefined
```

**Comment by fritzmg** [comment]
With the current code, the `elements.build_with_dependencies.html` is integrated into the page, before the `<ff-communication>` element is inserted into the DOM. This is a problem, because the `elements.build.js` seems to rely on the `<ff-communication>` element to be present.

I am guessing the `elements.build.js` needs to be changed, so that it listens for an event, before it can initialize itself.

**Comment by toarm** [comment]
The error messages you are encountering are related to dom/js loading order. 
Basically `<ff-campaing-landing element page-id="mylandingpage">`  is parsed before `<ff-communication>` element occurs. What happens is that ff-campaign-landing-page tries to send a request to FACT-Finder before the connection information is available through `<ff-communicaiont url="" version=""...>`. `e.url is undefined`  is just the raw error message thrown by the core. 

So somehow we have to ensure that `<ff-communicaiton>`  is the first FACT-Finder Web Component encountered in the dom. You can read about that [here](https://web-components.fact-finder.de/documentation/configuration).
What makes me more worried is the very last log entry. Could be an async loading issue. E.g. `webcomponents.lite-min.js` is loaded and `DOMContentLoad` + `WebComponentReady` event occurs before elements.build.js is fully loaded.

@a-laurowski can you double check the js loading approach considering this information. Could be probably worth deploying a staging system for me so I can investigate too.

**Comment by a-laurowski** [comment]
Hi @fritzmg 
Hi. I've created a new PR.
Right now only sid and uid attributes will be fetched via ajax. ff-communication component rendering is reverted to as it was

**Comment by fritzmg** [comment]
> So somehow we have to ensure that `<ff-communicaiton>` is the first FACT-Finder Web Component encountered in the DOM.

That's impossible though with user sections, since that will always happen later. As I said, the web component parsing would need to be initialized _after_ the `<ff-communication>` has been inserted.

> Right now only sid and uid attributes will be fetched via ajax. ff-communication component rendering is reverted to as it was.

Yeah, this may be the better solution anyway.

**Pull request merged**
