### PR TITLE
 keep_url_params should be select input field

### PR DESCRIPTION
**Pull request by michi-p**
- Solves issue: 
- Description: keep_url_params config should have boolean input field in admin backend
- Tested with Magento editions/versions: 2.1.5
- Tested with PHP versions: 7.1

### CODE REVIEW

**Comment by jaroslawweselski** [comment]
Hello,

As documentation says, keep-url-params is string parameter with default empty value. It can't be merged then.

https://web-components.fact-finder.de/api/ff-searchbox#tab=api

**Comment by fritzmg** [comment]
> https://web-components.fact-finder.de/api/ff-searchbox#tab=api

The link isn't working ;)

**Comment by jaroslawweselski** [comment]
@fritzmg Thank you for reporting the issue. For now workaround may be using Chrome or in case of Firefox, you should click API item from homepage, not from above URL.

@michi-p Why do you think keep-url-params should be boolean?

**Comment by toarm** [comment]
I've created an issue for that:
https://github.com/FACT-Finder-Web-Components/documentation/issues/67

**Comment by fritzmg** [comment]
> @michi-p Why do you think keep-url-params should be boolean?

What does the `keep-url-params` parameter expect? The documentation doesn't say.

**Pull request closed without merging**
